//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatusServer.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppEventType
    {
        public int Id { get; set; }
        public int ApplicationId { get; set; }
        public int Order { get; set; }
        public string Name { get; set; }
        public Nullable<int> EventTypeGroupId { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual AppEventTypeGroup AppEventTypeGroup { get; set; }
    }
}
