//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatusServer.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationVersion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationVersion()
        {
            this.AppEventLogs = new HashSet<AppEventLog>();
            this.AssertLogs = new HashSet<AssertLog>();
            this.ErrorLogs = new HashSet<ErrorLog>();
            this.TraceLogs = new HashSet<TraceLog>();
        }
    
        public string VersionNumber { get; set; }
        public int ApplicationId { get; set; }
        public int EnvironmentId { get; set; }
        public int ModuleId { get; set; }
        public System.DateTime FirstEncountered { get; set; }
        public System.DateTime LastEncountered { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppEventLog> AppEventLogs { get; set; }
        public virtual Application Application { get; set; }
        public virtual Environment Environment { get; set; }
        public virtual Module Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssertLog> AssertLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ErrorLog> ErrorLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraceLog> TraceLogs { get; set; }
    }
}
