//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatusServer.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    internal partial class Context : DbContext
    {
        public Context()
            : base("name=Context")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AncillaryData> AncillaryDatas { get; set; }
        public virtual DbSet<AppEventLog> AppEventLogs { get; set; }
        public virtual DbSet<AppEventType> AppEventTypes { get; set; }
        public virtual DbSet<AppEventTypeGroup> AppEventTypeGroups { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<ApplicationVersion> ApplicationVersions { get; set; }
        public virtual DbSet<AssertLog> AssertLogs { get; set; }
        public virtual DbSet<Environment> Environments { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<ObjectData> ObjectDatas { get; set; }
        public virtual DbSet<TraceLog> TraceLogs { get; set; }
        public virtual DbSet<ApiKey> ApiKeys { get; set; }
        public virtual DbSet<AuthInfo> AuthInfoes { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
    }
}
