//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatusServer.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    internal partial class StatusServerEntities : DbContext
    {
        public StatusServerEntities()
            : base("name=StatusServerEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Environment> Environments { get; set; }
        public virtual DbSet<Error> Errors { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<ObjectState> ObjectStates { get; set; }
    }
}
